### ISSUE TITLE
RTX Super Resolution turns off in full screen mode

### ISSUE THREAD

**Issue by FiftyFour7250** [emoose/VideoRenderer#31]
It works, but as soon as I switch to full screen mode, two seconds, and that's it, it turns off. When I exit the full screen, it immediately turns on again.

**Comment by FiftyFour7250** [comment]
Judging by what is written here, I am not the only one who has faced such a problem
https://github.com/emoose/VideoRenderer/issues/24#issuecomment-1912829735
And yes, I can confirm that Super Resolution turns on again not only when switching to windowed mode, but also if you just hover the cursor over the playback strip, but as soon as OSD disappears - Super Resolution turns off.

If enable the use of exclusive full screen in MPC VR settings, then even the appearance of OSD will not turn on Super Resolution

However, unlike what was written on the link, I do not have such a problem in the browser, whether it is playing a local video, YouTube, or anything else. Everything works perfectly in browser. So it's not "Nvidia issue", as he wrote.

**Comment by FiftyFour7250** [comment]
So far, the best workaround I've found is display the system time in OSD in the upper-left corner (turned on with the I button), it doesn't take up as much space as the playback bar at the bottom. Curiously, this makes it possible to instantly enable and disable Super Resolution by pressing a single key, which is useful for comparison.

**Comment by FiftyFour7250** [comment]
Well, I even managed to improve it. In the settings, you can customize the appearance of OSD, including transparency. The maximum value is 255, and if you select 255, then Super Resolution will not work, but if you select 254, then OSD is not visible, and Super Resolution works as it should in full screen, and it can still be turned on and off with one button.

**Comment by CornCorny** [comment]
Same thing is happening for me with the HDR when going fullscreen, maybe the super resolution as well but harder to tell for sure. Still shows active in NVCP but when I go fullscreen it definitely goes back to similar SDR image. Comparing scene for scene with Plex via chrome with that fullscreen it is definitely not as bright or detailed in the dark areas. As the last comment says, using MPC BE and pressing I for system time and changing transparency to 254 isn't a bad solution for now, or I'll just use plex/chrome at the moment. I also tested this with MPC HC and PotPlayer and it acted the same with them all. Perhaps there's some sort of driver setting somewhere that could address this but I can't figure it out.

**Comment by XcellMiguel** [comment]
Looks like this issue is fixed in driver 551.61 that introduces RTX HDR for games.
Now it works in fullscreen without having to put the overlay.

**Comment by FiftyFour7250** [comment]
@XcellMiguel Not for me. It's still the same, even though I'm on 551.61. But as I said, I even like. Because it makes possible to disable Super Resolution with one button.

**Comment by XcellMiguel** [comment]
> @XcellMiguel Not for me. It's still the same, even though I'm on 551.61. But as I said, I even like. Because it makes possible to disable Super Resolution with one button.

Also, I installed NVIDIA App beta that replaces GeForce Experience, maybe some changes in its overlay fixed that.

**Comment by FiftyFour7250** [comment]
@XcellMiguel  Oh, then maybe. I didn't install beta GeForce Experience app yet

**Comment by CornCorny** [comment]
For me the issue seems fixed on all three video players when updated to the new driver and updating to the new nvidia app. Cheers.

**Comment by abraraamer** [comment]
In MPC HC, I still have the same issue. When I right click in fullscreen mode, super res becomes active again. It seems some overlay has to be active for it to stay on. I tried to keep the time on but that doesn't help. I have an ultrawide monitor.

**Comment by inobrevi** [comment]
Hi!
I was using this feature (very nice), but for some reason I can't get it to work now.
I suspect that something might have changed with Nvidia drivers. My current driver version is 555.99.

Can someone who has it working update to current drivers and check if that breaks it?

**Comment by Dasa1508** [comment]
Hey guys I found a way to fix this problem. But I don't know if this will work for everybody, or how to fix it for those who only use one monitor, it certainly fixed it for me ever since I figured it out. If you're using 2 Monitors, try these following steps:

1. Open the Video, Stream, or whatever content you're trying to watch on your right monitor (in my case it's my main one) and put it into Fullscreen mode

The following step might seem a bit confusing at first, but if it works it works

2. Open the NVIDIA Control panel and now you'll have to place the window on the right side of your left monitor (for me it's my second monitor), I will attach a screenshot in which you'll see how to correctly place the window.
![screenshot](https://github.com/user-attachments/assets/9d1df049-c39c-40ba-b59f-e530d414220d)
[IMPORTANT: Do not place it on the left half of the monitor. For some reason it instantly stops working as soon as you do so. I also encountered the same problem when maximizing the control panel window.]

3. Once the control panel is opened and placed in the right location you can start the video
4. Now all you need to do is to click onto the control panel (while the video is running) to put it into focus

And that's it. As long as you don't click back into your browser again (or get it focused through something else) you should be fine.

Sorry for my slightly poor English and my incredibly bad instructions, but I hope this helped at least some of you enjoying VSR in Fullscreen.
I've tested it on Windows 10 (worked perfectly fine) and Windows 11, and it should do the trick on both systems. And it should also work with the non-Beta Geforce Experience app because the beta one doesn't really change the control panel in any way yet.

Please feel free to comment if it works out for you guys or not.

Edit: I'm using Chrome and haven't tried it in other browsers yet

**Comment by MikkoHalonen** [comment]
I had the same HDR issue. It was brighter when there was OSD on the screen or if I was not in fullscreen. 

Updating the nvidia drivers or geforce experience -> nvidia app didn't help, but uninstalling both did. Even after I returned to aug 20/2024  drivers and nvidia app beta, the issue didn't return. 

After the issue was fixed, the HDR content plays at the brightness that was lower than when there was OSD on screen. As far as I can tell, this is the correct brightness.

**Comment by clsid2** [comment]
So you have basically done a clean install to reset the NVIDIA settings.

Enabling "image scaling" in NVIDIA settings can cause the fullscreen problem. Keep that disabled. It is a stupid option to use globally anyway.

**Comment by cdiehm** [comment]
a work around i figured out to keep super resolution on is to turn on live captions

**Comment by oluittv** [comment]
I lost 6 hours of sleep so someone sees this and doesn't have to go through the same roller-coaster of installing and reinstalling different versions, different drivers, triple checking configurations, none of that solves it.

All you have to do is go to the MPC-HC or BE executable -> right-click -> properties -> compatibility -> use legacy display ICC color management [✔️]

EDIT: I just realized this makes the program run with a warmer tone than it's supposed to. Back at square one.
